// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zvpdaeogjwstsyokfriq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cGRhZW9nandzdHN5b2tmcmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDk5NTgsImV4cCI6MjA2MTg4NTk1OH0.Kdouok3lxp8x7K0Mo_t0LejHQgyqR_dN36w151ysj10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);